apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: io-heavy-app
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: io-heavy-app
spec:
  parentRefs:
  - name: io-heavy-app
  hostnames:
  - "io-heavy.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: io-heavy-app
      port: 80